### ISSUE TITLE
希望增加typescript支持

### ISSUE THREAD

**Issue by Barry-Flynn** [dingshaohua-cn/vuepress-plugin-anchor-right#2]
否则在引入该依赖时报`无法找到模块“XXX”的声明文件错误`，类似于这种情况 https://blog.csdn.net/xiebaochun/article/details/122458063

**Comment by dingshaohua-cn** [comment]
好的  等抽空我支持 之后  这个issue就关闭掉
暂时先@ts-nocheck

**Comment by dingshaohua-cn** [comment]
> 否则在引入该依赖时报`无法找到模块“XXX”的声明文件错误`，类似于这种情况 https://blog.csdn.net/xiebaochun/article/details/122458063

好的 等抽空我支持 之后 这个issue就关闭掉
暂时先@ts-nocheck

**Comment by itlemon** [comment]
求支持typescript支持。

**Comment by itlemon** [comment]
> > 否则在引入该依赖时报`无法找到模块“XXX”的声明文件错误`，类似于这种情况 https://blog.csdn.net/xiebaochun/article/details/122458063
> 
> 好的 等抽空我支持 之后 这个issue就关闭掉 暂时先@ts-nocheck

大佬合适支持typescript呀

**Comment by dingshaohua-cn** [comment]
ts是支持的 `不知道为什么你们都遇到这个问题？！
```js
import { defineUserConfig } from 'vuepress'
import vuepressPluginAnchorRight from 'vuepress-plugin-anchor-right';

export default defineUserConfig({
  lang: 'zh-CN',
  title: '你好， VuePress ！',
  description: '这是我的第一个 VuePress 站点',
  plugins: [
    [vuepressPluginAnchorRight()],
  ]
})
```
